item_fx:
  daily_range:  'RNG01'
  daily_return: 'RTN01'
  risk_1m:  'RSK01'
  risk_2m:  'RSK02'
  risk_3m:  'RSK03'
  risk_6m:  'RSK06'
  risk_12m: 'RSK12'
  risk_24m: 'RSK24'
  risk_36m: 'RSK36'
  risk_48m: 'RSK48'
  risk_60m: 'RSK60'
  range_5d_avg:   'AVG01'
  range_25d_avg:  'AVG02'
  range_75d_avg:  'AVG03'
  range_100d_avg: 'AVG04'
  rate_5d_avg:    'AVG11'
  rate_25d_avg:   'AVG12'
  rate_75d_avg:   'AVG13'
  rate_100d_avg:  'AVG14'

item_price:
  open_price:     'PRC01'
  high_price:     'PRC02'
  low_price:      'PRC03'
  close_price:    'PRC04'
  volume:         'PRC05'
  prev_price:     'PRC06'
  changes:        'PRC07'
  high_in_1year:  'PRC20'
  low_in_1year:   'PRC21'
  chart_image:    'PRC50'
  trade_time:     'PRC51'
